project:
  type: website
  output-dir: docs

website:
  title: "André Meichtry"
  site-url: "https://mcdr65.github.io/myblog/"
  description: "This is André Meichtry's personal Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mcdr65
      - icon: rss
        href: index.xml
      - text: Ressources
        menu:
          - text: R Weekly
            href: https://rweekly.org/
          - text: R Bloggers
            href: https://www.r-bloggers.com/
      - text: Archive
        href: archive.qmd

format:
  html:
    theme:
      light: litera
      dark: cyborg
    css: styles.css
    code-link: true